#pragma once

#define IDI_ICON 101
#define IDI_TEXT_ICON 102

#define IDC_POINTER 201

// #ifdef APSTUDIO_INVOKED
// #ifndef APSTUDIO_READONLY_SYMBOLS
// #define _APS_NEXT_RESOURCE_VALUE 102
// #define _APS_NEXT_COMMAND_VALUE 40001
// #define _APS_NEXT_CONTROL_VALUE 1001
// #define _APS_NEXT_SYMED_VALUE 101
// #endif // !APSTUDIO_READONLY_SYMBOLS
// #endif // APSTUDIO_INVOKED